# Dev overrides - automatically loaded with: docker compose up
# NEVER USE IN PRODUCTION
services:
  mongodb:
    ports:
      - "27018:27017"

  backend:
    environment:
      FLASK_ENV: development
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --debug
    develop:
      watch:
        - path: ./backend
          action: rebuild

  frontend:
    volumes:
      - ./src:/app/src
    develop:
      watch:
        - path: ./src
          action: rebuild
